steps:
    - id: "Build backend image"
      name: "gcr.io/cloud-builders/docker"
      args: ["build", "-t", "gcr.io/$PROJECT_ID/dankmemeclassifier-backend:$COMMIT_SHA", "./backend"]

    - id: "Push backend image"
      name: "gcr.io/cloud-builders/docker"
      args: ["push", "gcr.io/$PROJECT_ID/dankmemeclassifier-backend:$COMMIT_SHA"]

    - id: "Deploy backend"
      name: "gcr.io/cloud-builders/gcloud"
      args: 
        - "run"
        - "deploy"
        - "dankmemeclassifier-backend"
        - "--image"
        - "gcr.io/$PROJECT_ID/dankmemeclassifier-backend:$COMMIT_SHA"
        - "--region"
        - "us-east1"
        - "--platform"
        - "managed"
        - "--allow-unauthenticated"
        - "--memory"
        - "2G"  # Need more memory to be able to handle loading the ML model/images into memory (2GB is the max) 

timeout: 1800s
images: ["gcr.io/$PROJECT_ID/dankmemeclassifier-backend:$COMMIT_SHA"]
